### ISSUE TITLE
Pull commits from Rallysf fork

### ISSUE THREAD

**Issue by joeytheman** [ahawkins/cashier#10]
Can you take a look at Rallysf branch and see about pulling in some of their commits?  

I believe https://github.com/rallysf/cashier/commit/8ac3725a2351e966b7267e6c24f90d89f14a9181 will solve issues #6 and #8.

**Comment by joeytheman** [comment]
I forked Rallysf branch and fixed the test framework among a few other changes.  Let me know if you would like pull requests. https://github.com/joeytheman/cashier.git

**Comment by ahawkins** [comment]
Can you send a PR? The commit looks good. 

EDIT: Nevermind. This repo doesn't even have `cashier/application_controller` nor does it integrate directly with `ActionController`. What's the point?

**Comment by joeytheman** [comment]
They changed a few things. See 641e1f41ab5dcbcea83acc7d169754fc93ef603b .

**Comment by joeytheman** [comment]
Any update on this?

**Comment by ahawkins** [comment]
@joeytheman have them send a PR and I will review it.
