### ISSUE TITLE
ApplicationController methods not inherited when installing Gem

### ISSUE THREAD

**Issue by constantm** [ahawkins/cashier#12]
Just stumbled across a weird issue - when installing the Gem, it seems I'm not able to access any methods defined in ApplicationController from other controllers. Any ideas why this would happen?

**Comment by ahawkins** [comment]
This does not make any sense. Can you provide a test app?

**Comment by tinylox** [comment]
I have a similar problem I am using cashier along with inherited resources. I think that may have something to do with it. 
Looking at the ApplicationController definition in a pry session shows the cashier extensions to ApplicationController but my own apps local ApplicationController methods are not present.  

InheritedResources::Base descends from ::ApplicationController and I think in this instance it is the inheriting from the cashier implementation before the local app version can add its methods to the class leading to other classes not having visibility to the apps ApplicationController defined methods. Ill see if I can put together an example app with this problem.

**Comment by tinylox** [comment]
Upon further investigation it appears that the problem is with the version of the gem hosted at rubygems.org. 
When updating the Gemfile to point to the latest on master things work fine as the application_controller.rb file has been removed. Is what is on master right now stable ? If so perhaps a minor version bump and deploy to rubygems is in order?

**Comment by ahawkins** [comment]
Yes it seems so. I will sort it out and release a new version.

**Comment by ahawkins** [comment]
> If so perhaps a minor version bump and deploy to rubygems is in order?

@tinylox 0.4.1 just deployed. Sorry about that and for the delay :(
